### PR TITLE
Add optee_benchmark repository for rpi3 and qemu_v8

### PR DESCRIPTION
**Pull request by igoropaniuk**
`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by igoropaniuk** [comment]
Applied tags & rebased

**Comment by igoropaniuk** [comment]
Added optee_benchmark rep to rpi3.xml

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by igoropaniuk** [comment]
Applied tags & rebased

**Pull request merged**
