### PR TITLE
qemu_v8: Pin optee_rust to the latest version

### PR DESCRIPTION
**Pull request by DemesneGH**
Pin optee_rust to "Fix cargo error".
That fixed the Rust CI issue: https://github.com/OP-TEE/optee_os/pull/5705#issuecomment-1352816679

### CODE REVIEW

**Comment by DemesneGH** [comment]
@jforissier Please check out this PR. Thanks!

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@DemesneGH thanks for the quick fix! Can you please add the error message to the commit description? It can be helpful.

```
   error[E0658]: use of unstable library feature 'str_strip': newly added
```

WIth that:
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org>`
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by DemesneGH** [comment]
@jforissier Done.

**Pull request merged**
