### PR TITLE
Add support for Juno

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Change-Id: I735cbe71c3f036b4ac6a1f2ec9c8d97c88557620
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

Depends on https://github.com/OP-TEE/build/pull/45

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by pascal-brand-st-dev** [comment]
@jens please add the tags

**Comment by jens** [comment]
Wrong jens...

**Comment by pascal-brand-st-dev** [comment]
@jenswi-linaro please add the tags

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
