### PR TITLE
rpi3: add rpi3 firmware remote

### PR DESCRIPTION
**Pull request by igoropaniuk**
`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by igoropaniuk** [comment]
@jbech-linaro specified the same revision of rpi3 firmware, as we used before, as I've faced strange issues in gpio drivers. I guess there were some major changes in legacy bootloaders, that are responsible for initialising SoC.

```
[    4.895936] [<ffffff8008085568>] el1_da+0x18/0x70
[    4.904058] [<ffffff80084107e4>] _gpiod_get_raw_value+0x3c/0x100
[    4.913532] [<ffffff800841379c>] gpiod_get_value_cansleep+0x34/0xb0
[    4.923302] [<ffffff8008562c58>] gpio_led_get+0x20/0x38
[    4.932001] [<ffffff8008561268>] led_update_brightness+0x28/0x50
[    4.941496] [<ffffff8008561cc8>] led_classdev_register.part.0+0x98/0xb8
[    4.951616] [<ffffff8008561e40>] led_classdev_register+0x100/0x140
[    4.961269] [<ffffff8008562d54>] create_gpio_led+0xe4/0x180
[    4.970288] [<ffffff8008562f60>] gpio_led_probe+0x170/0x3c8
[    4.979264] [<ffffff800846fe88>] platform_drv_probe+0x60/0xc8
[    4.988408] [<ffffff800846e21c>] driver_probe_device+0x204/0x2b0
[    4.997823] [<ffffff800846e384>] __driver_attach+0xbc/0xc0
[    5.006714] [<ffffff800846bedc>] bus_for_each_dev+0x74/0xb0
[    5.015696] [<ffffff800846d8e8>] driver_attach+0x30/0x40
[    5.024405] [<ffffff800846d3f8>] bus_add_driver+0x118/0x238
[    5.033345] [<ffffff800846e9e8>] driver_register+0x68/0x100
[    5.042275] [<ffffff800846fdac>] __platform_driver_register+0x54/0x60
[    5.052097] [<ffffff80089239fc>] gpio_led_driver_init+0x18/0x20
[    5.061365] [<ffffff8008082e7c>] do_one_initcall+0x94/0x1a0
[    5.070267] [<ffffff80088ebb2c>] kernel_init_freeable+0x1c4/0x264
[    5.079690] [<ffffff80086a43f0>] kernel_init+0x18/0x108
[    5.088210] [<ffffff8008085dc0>] ret_from_fork+0x10/0x50
```

**Comment by jbech-linaro** [comment]
Thanks for fixing the issue, lgtm.
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by igoropaniuk** [comment]
Tag applied and rebased, thanks!

PR is ready for merge

**Pull request merged**
