### PR TITLE
Update buildroot to 2020.08

### PR DESCRIPTION
**Pull request by jforissier**
Supports building with GCC 9.

Signed-off-by: Jerome Forissier <jerome@forissier.org>
Change-Id: Ieaa3a304ef3e414d0d067072d36e82a2eb2cc0e8

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
Hi all. Despite I expected no issues with such upgrades, testing on stm32mp1 pointed at least an issue in the partition table of the generated image. Seems not related to gcc9.2 even if I doubt the issue is related buildroot. I'll investigate. Could you please wait a bit before merging this change and https://github.com/OP-TEE/build/pull/438?

**Comment by jforissier** [comment]
@etienne-lms sure. Since this (and the GCC 9.2 update) affects all platforms, I'm happy to wait until this is tested well enough.

**Comment by etienne-lms** [comment]
Thanks @jforissier. Actually I've seen a weird thing in my setup. Buildroot was pointing to its master, not tag 2020.08. I'm rebuilding the whole thing and I am pretty confident there is no real issue. I'll tell you by then.

**Comment by etienne-lms** [comment]
Issue is indeed in the partition table of the generated image (stm32mp1 builds a raw SDcard image with a GPT partitioning). The issue comes from Buildroot 2020.08 has upgraded to genimage v13 which creates a hybrid MBR partition table (https://github.com/pengutronix/genimage/pull/96) for stm32mp1 platform. TF-A boot stage does not support hybrid MBR. After few investigation, this root cause is stm32mp1 partitioning description. I've created https://github.com/OP-TEE/build/pull/439 to fix the issue. Once merged, buildroot can be upgraded without issues regarding for stm32mp1.

**Comment by etienne-lms** [comment]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Pull request merged**
