### PR TITLE
fvp: replace edk2+grub with u-boot

### PR DESCRIPTION
**Pull request by balint-dobszay-arm**
Remove the edk2 and grub components and use u-boot instead.

### CODE REVIEW

**Review by jforissier — COMMENTED** [review]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by balint-dobszay-arm** [comment]
Thanks, tag applied

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by balint-dobszay-arm** [comment]
Thanks, tag applied

**Pull request merged**
