### PR TITLE
hikey: l-loader downloaded from https://github.com/96boards-hikey

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
Change-Id: I709b7c07e66b520e69b7395b93baf4ef56231365
Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
@vchong any comment from you about it?

`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vchong** [comment]
Lgtm. The 96b-hk branch has Jerome's PR that removed the sudo.
What about hikey_debian.xml? Might as well do them together and keep all the hikey*.xml in sync?

`Reviewed-by: Victor Chong <victor.chong@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
updated. stable version must be updated/sync only when setting release tags, so I do not update it now.

@jbech-linaro still ok for you?

**Comment by jbech-linaro** [comment]
@vchong hikey_debian.xml that's fine with me (not related to this l-loader, but there are a few patches missing on the linux branch for hikey_debian.xml, which is the reason I've been asking questions in another email).

`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Pull request merged**
