### PR TITLE
rockpi4: Update TF-A to v2.10.0

### PR DESCRIPTION
**Pull request by msgilligan**
This is to address https://github.com/OP-TEE/build/issues/769

### CODE REVIEW

**Comment by msgilligan** [comment]
Marking as DRAFT because I haven't tested yet.

**Comment by msgilligan** [comment]
I've tested the build (`make -j8 boot-img` on Debian 12 aarch64) and also verified that I can boot a Rock Pi 4b+ from an SD card with that image and run `xtest`. 

Removing DRAFT...

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jenswi-linaro** [comment]
Merged manually.

**Pull request closed without merging**
