### PR TITLE
fvp: Add hafnium component to enable running wih SPMC at EL2

### PR DESCRIPTION
**Pull request by sudeep-holla**
Let us add the hafnium component in order to enable building and testing SPMC at EL2. Also update TF-A to match Hafnium version at v2.10

### CODE REVIEW

**Comment by jforissier** [comment]
I'd rather have two separate commits. In any case:
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by sudeep-holla** [comment]
I can do that if that is the preference, I was being lazy I guess :).

**Comment by jforissier** [comment]
Well no big deal but having both changes in one patch makes it unclear if there is a dependency here, i.e., does the hafnium config require TF-A v2.10 or is v2.9 still OK? If not you should first add Hafnium then update TF-A. If yes, then do the opposite and mention it in the commit description ("fvp: update TF-A to v2.10": "In order to enable running with SPMC at EL2 with Hafnium in a subsequent commit, update TF-A to v2.10").

**Comment by sudeep-holla** [comment]
> Well no big deal but having both changes in one patch makes it unclear if there is a dependency here, i.e., does the hafnium config require TF-A v2.10 or is v2.9 still OK? If not you should first add Hafnium then update TF-A. If yes, then do the opposite and mention it in the commit description ("fvp: update TF-A to v2.10": "In order to enable running with SPMC at EL2 with Hafnium in a subsequent commit, update TF-A to v2.10").

I did the latter. In general, they are features  set compatible. Not sure if we can run hafnium at v2.10 keeping TF-A at v2.9, but some FF-A features got added in both and are needed to get the feature enabled in end-to-end stack. That is the reason why I bumped it to v2.10

**Pull request merged**
