### PR TITLE
Switch to upstream arm tf

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Depends on https://github.com/OP-TEE/build/pull/180

**Comment by jenswi-linaro** [comment]
Added patch for Juno also

**Comment by jforissier** [comment]
Nice!
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

(I'd rather not have the Change-Id tag btw).

**Comment by jenswi-linaro** [comment]
Change-Id tag removed, Acked-by tag added.

**Pull request merged**
