### PR TITLE
synquacer: add initial manifest

### PR DESCRIPTION
**Pull request by FulcronZ**
This provides initial manifest for DeveloperBox.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
@FulcronZ thanks for submitting this, the changes as such looks fine, but I'm having issues when running it:

```bash
...
build.py...
/media/jbech/SSHD_LINUX/devel/optee_projects/synquacer/edk2/CryptoPkg/Library/OpensslLib/OpensslLib.inf(-1): error 000E: File/directory not found in workspace
        openssl/e_os.h is not found in packages path:
        /media/jbech/SSHD_LINUX/devel/optee_projects/synquacer/edk2
        /media/jbech/SSHD_LINUX/devel/optee_projects/synquacer/edk2-platforms/.
        /media/jbech/SSHD_LINUX/devel/optee_projects/synquacer/edk2-non-osi
 

- Failed -
Build end time: 08:28:13, Jun.05 2019
Build total time: 00:00:02

Makefile:103: recipe for target 'edk2' failed
make: *** [edk2] Error 14
```
All things not cloned? Missing dependencies (apt-get)?

**Comment by FulcronZ** [comment]
@jbech-linaro Sorry for delayed response. 

EDK2 requires OpenSSL submodule. There are 2 ways to do this. 

```sh
# ask repo to fetch submodule
repo init ... --fetch-submodules
# fetch submodule manually
cd edk2
git submodule update --init
```

I'm not sure if a manifest file can tell repo to fetch submodules.

**Comment by jbech-linaro** [comment]
Fair enough, then it's something that needs to be specified in the build instructions for the device and I can see that you've already written that in https://github.com/OP-TEE/optee_docs/pull/24. I'll give this another try and come back here again later with my tag.

**Comment by jbech-linaro** [comment]
Btw, I did test with the submodule in edk2, and it built without any errors after doing that. That is what I'm able to test (since I have no developerbox myself).
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by FulcronZ** [comment]
Thanks for reviewing. Added R-B.

**Pull request merged**
