### PR TITLE
travis: Enable hikey960

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vchong** [comment]
Tag added. Thanks!

**Comment by jforissier** [comment]
Travis is failing because it expects to find `hikey960_stable.xml`. I suppose that file has to be created.
(But why would the CI script of this project depend on a stable snapshot? Don't we want to test the current state?)

**Comment by vchong** [comment]
So should I create `hikey960_stable.xml`, or wait for @jbech-linaro to comment if we should test current state instead? The latter seems more appropriate.

**Comment by jforissier** [comment]
Yeah, ideally `hikey960_stable.xml` would have to reflect our next (stable) release, so we'd better not create it now. Let's wait before merging this, until we can clarify the purpose of the `_stable` stuff in `.travis.yml`.

**Comment by jbech-linaro** [comment]
Yeah, I too think it is better to wait, hopefully we get somewhere with Linaro CI also soon ...

**Comment by jforissier** [comment]
@jbech-linaro why is Travis testing `_stable`?

**Comment by jbech-linaro** [comment]
> @jbech-linaro why is Travis testing _stable?

Mainly because updates to manifest are most often done when we are releasing, i.e, this was meant to be a way for you to trigger a sanity build test when changing all manifests for a release. Compare that to our "build.git" where we tend to add patches quite often (and therefore doesn't use _stable).

**Comment by jforissier** [comment]
Yeah. To be honest I don't see the point in having _stable manifests. Much better to use tags to identify what is stable (or branches, as I seem to recall that `repo` doesn't know how to check out a tag).
Then Travis could do what it is supposed to do as a CI tool, i.e. build the current state of the Git tree so that PRs can be tested properly.

**Comment by jbech-linaro** [comment]
I think you are right, it was (hate to say it ...) repo that wasn't able to deal with the tags "outside" the manifest that was the issue which made us create stable manifests. If we can change it suite are needs better, then why not? There is a comment at the bottom [here](https://groups.google.com/forum/#!topic/repo-discuss/IBgCUc4QaKg), which suggests using `refs/tags/<tagname>`. I'm pretty sure I tested that too and I couldn't get it to work. But it could be worth double check. If it works, we could get rid of the stable manifests and just tag everything.

**Comment by igoropaniuk** [comment]
@jbech-linaro I think as we have replaced `hello_world` git to `optee_examples` in all manifests, I suppose we should do what you suggested ASAP (as all makefiles in build.git expect that `<repo>/optee_examples` exists), because all further builds will basically fail.

**Comment by jbech-linaro** [comment]
> @jbech-linaro I think as we have replaced hello_world git to optee_examples in all manifests, I suppose we should do what you suggested ASAP

What did I suggest and what do you suggest to change? :) Didn't we conclude that we couldn't use tags?

**Comment by jforissier** [comment]
@jbech-linaro integration should test `foo.xml` not `foo_stable.xml`.

**Comment by jbech-linaro** [comment]
@jforissier , right if we can get it to work (i.e., check out stable tagged manifests using repo). Igor, please give it a try and if it works, then let's switch at next release. Sounds like a plan?

**Comment by vchong** [comment]
@jforissier Ok to merge this now?

**Comment by jforissier** [comment]
@vchong yes

**Pull request merged**
