### PR TITLE
Switch to GitHub for strace

### PR DESCRIPTION
**Pull request by jforissier**
SourceForge is unreliable [1]. Use GitHub instead.

Change-Id: I73241adf4a0ce9b0a8985914ee4523f1d46e9207
Link: [1] https://travis-ci.org/OP-TEE/build/jobs/342160257#L621-L629
Suggested-by: Joakim Bech <joakim.bech@linaro.org>
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
Note: fixed wrong URL in `qemu_v8.xml` (extra `/strace`).

**Comment by jbech-linaro** [comment]
Not related to this PR and I'm not sure if repo will be used in the future, but since more and more gits are cloned directly from GitHub we could also in the future consider to reduce the amount of remotes to just use "github" as one remote replacing all individual GitHub remotes we are currently using. In that case you use a longer `name` instead (the full GitHub name). Then it would look something like I've done [here](https://github.com/jbech-linaro/manifest/blob/v8m/default.xml).

**Comment by jforissier** [comment]
@jbech-linaro yep that would be good

**Pull request merged**
