### PR TITLE
hikey960: initial commit

### PR DESCRIPTION
**Pull request by vchong**
Not to be used until build.git is updated.

### CODE REVIEW

**Comment by vchong** [comment]
Depends on https://github.com/linaro-swg/gen_rootfs/pull/24 and https://github.com/linaro-swg/patches_hikey/pull/6.

Build.git PR submitted: https://github.com/OP-TEE/build/pull/167

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vchong** [comment]
Rebased and tag applied. Thanks!

**Comment by jforissier** [comment]
Should [`.travis.yml`](https://github.com/OP-TEE/manifest/blob/master/.travis.yml#L35-L43) be updated to build HiKey960 too?

**Pull request merged**
