### PR TITLE
versal: initial manifest

### PR DESCRIPTION
**Pull request by ldts**
Initial manifest to build the Versal ACAP platform.

Tested on the Versal ACAP vck190.

While upstreaming progresses, two of the repositories reference Foundries.io so users can validate all the platform features (eFuse, TRNG, crypto, PUF etc)

It is the expectation that over the coming months - as merges take place - these two repositories will point to the AMD/Xilinx and OP-TEE projects instead.

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by ldts** [comment]
maybe I should explicitly point to the 3.18 branch of OP-TEE repos?

**Comment by jbech-linaro** [comment]
> maybe I should explicitly point to the 3.18 branch of OP-TEE repos? while the upstreaming of the FIO repos takes place that is....

I think this should be tracking upstream, we'll tag all manifests when we do the stable releases.

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by ldts** [comment]
> > maybe I should explicitly point to the 3.18 branch of OP-TEE repos? while the upstreaming of the FIO repos takes place that is....
> 
> I think this should be tracking upstream, we'll tag all manifests when we do the stable releases.

sorry what do you mean? do I need to change the Foundries.io repos? this PR uses two Foundries.io repositories: 1) OP-TEE 3.18 + Versal full set and 2) TF-A v2.7 with a single/one-liner patch to jump to OP-TEE (this workaround/hack is required for the time being)...can we then keep it as is for the time being?

**Comment by jbech-linaro** [comment]
> > > maybe I should explicitly point to the 3.18 branch of OP-TEE repos? while the upstreaming of the FIO repos takes place that is....
> > 
> > 
> > I think this should be tracking upstream, we'll tag all manifests when we do the stable releases.
> 
> sorry what do you mean? do I need to change the Foundries.io repos? this PR uses two Foundries.io repositories: 1) OP-TEE 3.18 + Versal full set and 2) TF-A v2.7 with a single/one-liner patch to jump to OP-TEE (this workaround/hack is required for the time being)...can we then keep it as is for the time being?

This is good as it is, that is what I was trying to say (hence my R-B tag). Hopefully it'll be possible to switch over to upstream repo instead of Foundries.io repos on the future. My comment about tagging was more of a generic comment. I.e., the other ones that are prefixed with "optee_" etc. Those will get a stable tag once we make the normal OP-TEE release.

**Comment by ldts** [comment]
updated with tags

**Comment by ldts** [comment]
> > > > maybe I should explicitly point to the 3.18 branch of OP-TEE repos? while the upstreaming of the FIO repos takes place that is....
> > > 
> > > 
> > > I think this should be tracking upstream, we'll tag all manifests when we do the stable releases.
> > 
> > 
> > sorry what do you mean? do I need to change the Foundries.io repos? this PR uses two Foundries.io repositories: 1) OP-TEE 3.18 + Versal full set and 2) TF-A v2.7 with a single/one-liner patch to jump to OP-TEE (this workaround/hack is required for the time being)...can we then keep it as is for the time being?
> 
> This is good as it is, that is what I was trying to say (hence my R-B tag). Hopefully it'll be possible to switch over to upstream repo instead of Foundries.io repos on the future. My comment about tagging was more of a generic comment. I.e., the other ones that are prefixed with "optee_" etc. Those will get a stable tag once we make the normal OP-TEE release.

yes. I understood your point after I asked the question. ok cool. thanks

**Comment by ldts** [comment]
will send the doc update in a bit.

**Pull request merged**
