### PR TITLE
examples: use optee_examples instead of hello_world

### PR DESCRIPTION
**Pull request by igoropaniuk**
Relates to:
https://github.com/linaro-swg/optee_examples/pull/1
https://github.com/OP-TEE/build/pull/170

`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

### CODE REVIEW

**Comment by jforissier** [comment]
s/optee_benchmark/optee_examples/

**Comment by igoropaniuk** [comment]
@jforissier thanks

the shadow of benchmark task is still following me :)

**Comment by jbech-linaro** [comment]
Header of commit message is missing an `of`
`examples: use optee_examples instead hello_world`
should be?
`examples: use optee_examples instead of hello_world`

**Comment by igoropaniuk** [comment]
Tags applied and rebased

**Pull request merged**
