### PR TITLE
benchmark: support for HiKey6220 and TI SoCs(am57xx, dra7xx)

### PR DESCRIPTION
**Pull request by igoropaniuk**
Relates to: https://github.com/OP-TEE/build/pull/194
`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Even though I've seen it in several places I think it is HiKey 620 and not HiKey 6220 (it comes from HiSilicon Kirin 620 SoC ), @jforissier, do you agree?
Besides that ...
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
@jbech-linaro correct (as far as I can tell!).

**Comment by igoropaniuk** [comment]
@jbech-linaro @jforissier Pretty interesting that we are using dts with such filename for HiKey620 build `arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts` (Check https://github.com/OP-TEE/build/blob/master/hikey.mk#L157 ). Also I mentioned while ago the same "HiKey6220" title in LAVA device list.

 I guess that both HiKey620 and HiKey6220 stand for the same physical board, no?

**Comment by jforissier** [comment]
Ah, yes, now I understand. The "marketing" name of the SoC is "Kirin 620", but the technical reference (the chip marking) is "Hi6220". So both designations can be considered OK.

**Comment by igoropaniuk** [comment]
Tag applied and rebased, thanks!

**Pull request closed without merging**
