### PR TITLE
rpi3: use rpi3 firmware stable branch

### PR DESCRIPTION
**Pull request by igoropaniuk**
`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

### CODE REVIEW

**Comment by igoropaniuk** [comment]
Fixes repo error, when `--clone-depth="1"` and revision is specified as SHA1 hash

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by igoropaniuk** [comment]
@jbech-linaro 

After some testing, find the an with GPIO driver (that I've mentioned about on Friday), switched to the latest firmware (before changes, that introduced this issue, were added).

Verified "repo init/repo sync" from scratch with this changes, seems that everything is OK

**Comment by igoropaniuk** [comment]
@jbech-linaro we could switch to the latest stable firmware when we update linux kernel version, used for RPi3 build (where gpio driver takes into account new API in the legacy rpi3 firmware)

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by igoropaniuk** [comment]
Tag applied and ready for merge! THanks

**Pull request merged**
