### PR TITLE
Juno environment

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Haven't tested it, but it looks sane from reading the xml-file.
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jbech-linaro** [comment]
FYI, since I wrote the comment I have test built using the Pascal's manifest and build pull request. I didn't notice any problem when building. Jens and I will make a test run tomorrow morning.

**Comment by cedric-chaumont-st-dev** [comment]
Tested-by: Cedric Chaumont cedric.chaumont@linaro.org (ARM Juno board)
48211 subtests of which 0 failed
701 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by pascal-brand-st-dev** [comment]
https://github.com/OP-TEE/manifest/pull/17 is cleaner

**Pull request closed without merging**
