### PR TITLE
hikey+debian: Adjust for upstream arm-tf

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
The patch seem to do a little more than just switch to upstream ARM-TF, please update the commit message.

**Comment by vchong** [comment]
Erm, any suggestions? `Update repos required to use upstream arm-tf`?

**Comment by jenswi-linaro** [comment]
Just listing them in the commit message and why they are needed.

**Comment by vchong** [comment]
@jenswi-linaro Commit message updated and also separated the burn-boot part out to a different commit for clarity. Also forced push the changes since the commit message was updated. Hope it's ok. Thanks!

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by vchong** [comment]
Thanks! Tag added but please don't merge until https://github.com/OP-TEE/build/pull/187 is ready as well.

**Comment by vchong** [comment]
OP-TEE/build#187 closed and replaced by OP-TEE/build#191.

**Pull request merged**
