### PR TITLE
AMD/Xilinx Versal ACAP: update to upstream tree

### PR DESCRIPTION
**Pull request by ldts**
All xtests pass with 3.20

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by ldts** [comment]
@nathan-menhorn just a heads up, after the 3.20 update we can/should switch to upstream.

**Comment by ldts** [comment]
@jforissier please could you pick this?

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by ldts** [comment]
thanks, having forks is a sign of failure so glad we got rid of it...

**Comment by nathan-menhorn** [comment]
> @nathan-menhorn just a heads up, after the 3.20 update we can/should switch to upstream.
> 
> I validated with https://optee.readthedocs.io/en/latest/building/devices/versal.html
> 
> One thing to notice is that in upstream, defining CFG_VERSAL_FPGA_DDR_ADDR is enough for the TEE to attempt to program the FPGA (before we used to have an additional knob..FPGA_INIT or something similar). Just in case your builds are pointing to some FPGA firmware that might lock the kernel.

Hi @ldts thanks for the heads up. Please send me a a ping on email or slack when the factory has switched over.

**Pull request merged**
