### PR TITLE
stm32mp1: bump U-Boot to 2022.10

### PR DESCRIPTION
**Pull request by jneuhauser**
The recent added board stm32mp157c-dhcom-pdk requires a dts fix [1] to not hang on boot

[1] https://source.denx.de/u-boot/u-boot/-/commit/48d9eaf6826a1816c5f9839a564ea6338da609a7

Signed-off-by: Johann Neuhauser <jneuhauser@dh-electronics.com>

Support of the boards stm32mp157c-dhcom-pdk and stm32mp157a-dhcor-avenger96  for the **OP-TEE developer setup** is completed after merging https://github.com/OP-TEE/manifest/pull/223 and https://github.com/OP-TEE/manifest/pull/219.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
@etienne-lms , this is something for you to chime in on.

`Acked-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jneuhauser** [comment]
Tag applied, thanks

**Comment by etienne-lms** [comment]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>` with `Link:` tags for [1] and [2] references in commit log.

**Comment by jneuhauser** [comment]
Tag applied and using `Link:` for references, thanks.

**Comment by jneuhauser** [comment]
Removed the empty line between tags like in #223

**Comment by jforissier** [comment]
@jneuhauser now there is a conflict due to the fact I just merged #223, would you mind addressing it? Thanks!

**Comment by jneuhauser** [comment]
@jforissier Rebased on master and addressed conflict. Thanks.

**Pull request merged**
